trigger:
  branches:
    include:
      - master
      - dev
      - feature/*
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master
      - dev

jobs:
  - job: macOSX
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - script: ./build.sh --target AzureDevOps --verbosity diagnostic --settings_skipverification=true
        displayName: Cake.Recipe